// alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
// leads types
export const GET_LEADS = 'GET_LEADS';
export const GET_LIKED_LEADS = 'GET_LIKED_LEADS';
export const GET_ARCHIVED_LEADS = 'GET_ARCHIVED_LEADS';
export const UPDATE_LEADS = 'UPDATE_LEADS';
export const VIEW_LEAD = 'VIEW_LEAD';
export const HANDLE_LIKE_LEAD = 'HANDLE_LIKE_LEAD';
export const HANDLE_ARCHIVE_LEAD = 'HANDLE_ARCHIVE_LEAD';
export const REMOVE_LEADS = 'REMOVE_LEADS';
export const ARCHIVE_LEAD = 'ARCHIVE_LEAD';
export const UNARCHIVE_LEAD = 'UNARCHIVE_LEAD';
export const SHOW_DETAILED_LEAD = 'SHOW_DETAILED_LEAD';
export const CLEAR_DETAILED_LEAD = 'CLEAR_DETAILED_LEAD';
export const SET_PAGE = 'SET_PAGE';
export const SET_RESET_PASSWORD_TOKEN = 'SET_RESET_PASSWORD_TOKEN';
export const CHECK_RESET_PASSWORD_TOKEN = 'CHECK_RESET_PASSWORD_TOKEN';
export const REMOVE_RESET_PASSWORD_TOKEN = 'REMOVE_RESET_PASSWORD_TOKEN';
export const GET_STRIPE_SUBSCRIPTION = 'GET_STRIPE_SUBSCRIPTION';
export const GET_PAYMENT_DETAILS = 'GET_PAYMENT_DETAILS';
